#! /bin/bash

DESTINATION=$1	
read -p "enter a file prefix:" FILE_PREFIX

if [ -z $DESTINATION ]; then
	echo "no path provided, default to ~/Documents/temp"
	DESTINATION=~/Documents/temp
fi 

mkdir -p $DESTINATION
cd $DESTINATION

# this is a comment

touch ${FILE_PREFIX}{1..10}.txt
echo done # this is a comment
